name: Generate Contribution City

on:
  schedule:
    - cron: "0 1 * * *" # Har kuni 06:00 Asia/Tashkent (UTC+5) => 01:00 UTC
  workflow_dispatch:

jobs:
  build:
    if: github.repository != 'contribution-city'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate Contribution City
        run: node generate-city.js
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A .
          if git commit -m "Update contribution city" ; then
            git push origin HEAD:${{ github.ref_name }}
          fi
